#!/usr/bin/env python
'''
\x1b[1mUsage:\x1b[0m
    {0} <t0> <t1> ... <tn>
    Where <t0>, <t1>, ... <tn> are latency files (the trivial standard
    output of the 'ping' program redirected on a file). You must provide
    at least one latency file.

\x1b[1mInformation:\x1b[0m
    Builds a gnuplot-compatible list of throughputs basing on the input
    files.

\x1b[1mNote:\x1b[0m
    The program writes on stdout the plotting request for gnuplot. Try to
    launch like this:
        {0} <params> | gnuplot -persist

'''

import sys
import pingparser
import utils

from itertools import izip as zip, \
                      count, islice
def build_data (*files):
    for fn, f in files:
        times = list(pingparser.PingParser(f))
        avg = utils.average(times)
        yield fn, avg, utils.variance(times, avg), \
              utils.quartiles(times), min(times), max(times)

def main (argv=None):
    if not argv: argv = sys.argv

    progname = argv.pop(0)
    if len(argv) < 1:
        sys.stderr.write(__doc__.format(progname))
        return 1

    files = map(lambda fn : (fn, open(fn, 'rt')), argv)
    for fn, avg, var, quarts, vmin, vmax in build_data(*files):
        print 'File:', fn
        print 'Average:', avg
        print 'Variance:', var
        print 'Quarts:', quarts
        print 'Min:', vmin
        print 'Max:', vmax

    for f in files: f[1].close()

    return 0


if __name__ == '__main__':
    sys.exit(main())

