#!/usr/bin/env python
'''
\x1b[1mUsage:\x1b[0m

    {0} <l0> [<l1> ...]

    Where <l0>, <l1> ... are the names of "latency" files (i.e. ping
    outputs redirected on a file).

'''

import sys
from pingparser import PingParser
import utils

from itertools import izip as zip, \
                      imap as map, \
                      izip_longest as zipl, \
                      count, \
                      islice

import matplotlib.pyplot as plt

class BoxPlotter :

    def __init__ (self, exps):
        exps_files = list(map(lambda fn : (fn, open(fn, 'rt')), exps))
        self.parsers = map(lambda (fn, fd) : PingParser(fd), exps_files)
        self.files = exps_files

    def show (self):
        plt.boxplot(tuple(map(list, self.parsers)), sym='')
        plt.setp(plt.gca(), 'xticklabels', list(map(lambda (fn, fd) : fn,
                                                    self.files)))
        plt.show()

    def __del__ (self):
        for fn, f in self.files:
            f.close()

def main (argv=None):
    if not argv: argv = sys.argv

    progname = argv.pop(0)
    if len(argv) < 1:
        sys.stderr.write(__doc__.format(progname))
        return 1

    BoxPlotter(argv).show()

    return 0


if __name__ == '__main__':
    sys.exit(main())

